trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: buildAndPush
  displayName: 'Build and push docker images'
  steps:
  - script: docker login -u ${REPOSITORY_PREFIX} -p ${DOCKER_PASSWORD}
    env:
      DOCKER_PASSWORD: $(docker_password)
    displayName: 'Login to dockerhub'
  - script: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${REPOSITORY_PREFIX}
    displayName: 'Build docker images'
  - script: ./scripts/pushImages.sh
    displayName: 'Publish docker images'
- job: deployToK8s
  displayName: 'Deploy to AKS'
  steps:
  - script: ./terraform/all.sh